require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :deterministic_uuids => false

target 'ParticleAAExample' do
  use_frameworks! :linkage => :static
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod "Thresh", '2.0.3'
  pod "ParticleMPCCore", '2.0.3'
  pod "ParticleAuthCore", '2.0.3'
  pod "AuthCoreAdapter", '2.0.3'
  
  pod 'ParticleNetworkBase', '2.0.3'
  pod 'ParticleNetworkChains', '2.0.3'
  pod 'ParticleAA', '2.0.3'

  pod 'ParticleConnect', '2.0.3'
  pod 'ConnectWalletConnectAdapter', '2.0.3'
  pod 'ConnectSolanaAdapter', '2.0.3'
  pod 'ConnectEVMAdapter', '2.0.3'
  pod 'ConnectCommon', '2.0.3'
  pod 'ConnectPhantomAdapter', '2.0.3'

  pod 'SwiftyUserDefaults', :git => 'https://github.com/SunZhiC/SwiftyUserDefaults.git', :branch => 'master'
  pod 'WalletConnectSwiftV2', :git => 'https://github.com/SunZhiC/WalletConnectSwiftV2.git', :branch => 'particle'
  pod 'SkeletonView', :git => 'https://github.com/SunZhiC/SkeletonView.git', :branch => 'main'


  target 'ParticleAAExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    
    installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            end
          end
  end
  
end
